### ISSUE TITLE
Publication of government related email addresses

### ISSUE THREAD

**Issue by KKennington** [tuvandm/data_dashboard#1]
This repo contains a large amount of email addresses linked to government domains, which by being in a public repo are open to abuse. Please either remove these from your repo, or change the repo visibility to private to protect the individuals email addresses. Those with an @nhs.net domain will be reported to the central management team of that domain

**Comment by tuvandm** [comment]
All the emails are were removed prior to uploading and masked with "no_email@for_you.com"

Could you please point out the specific document with emails??

**Comment by KKennington** [comment]
The emails are in the following:
https://github.com/tuvandm/data_dashboard/blob/main/Coupons-Export.csv

**Comment by tuvandm** [comment]
Oh wow!! Thank you for the catch! I am editing the file now to remove all emails!

**Comment by KKennington** [comment]
Thank you for the prompt response. I will advise our SECOPS team and the national NHS.net admins at Accenture. I also flagged this to the NHS Digital Cyber Security Operations service, who also monitor nhs.net for suspicious activity

**Comment by KKennington** [comment]
There are also quite a few nhs.net emails that are no longer in use, so how were users of whatever  you are building/testing being kept up to date, or removed when the email is no longer in use?

**Comment by tuvandm** [comment]
The dataset is an old dataset. The emails would have been collected when those users signed up to a specific service. For some reason their emails were also added to coupon description, but that should not have happened. The emails are not needed for any part of this tool. 

All emails have now been removed. Thank you for catching this error!

**Comment by tuvandm** [comment]
To clarify, the emails tagged along with the rest of the data even though they were not needed for the tool. The email columns were masked out right away, however, some coupons were linked to specific emails, and the site admin must have included their emails in the description for some reason; Since "coupon description" is not an email column, it went undetected and the emails remained in the dataset. But again, at no point were those emails used by the tool.

**Comment by KKennington** [comment]
Thank you for resolving this so quickly

**Comment by tuvandm** [comment]
Thank you to you for catching this; I'd hate for private/sensitive data to get out because I failed to thoroughly clean/mask my data.
